apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-web-app
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: python-app
        image: yatin0303/python-web-app:v1.0
        ports:
        - containerPort: 80
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"      
            cpu: "100m"       
          limits:
            memory: "256Mi"     
            cpu: "500m"      
